# docker-compose.yml

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      SECRET_KEY: secretkey
    volumes:
      - .:/app  # Mount the current directory to /app in the container
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "80:80"
