version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-multivector-image:1.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: 123!z2
    volumes:
      - multivector-app-data:/app
    user: "${UID}:${GID}"
    networks:
      - data-multivector-network

  nginx:
    image: nginx:latest
    volumes:
      - /home/ansible/github/ssl-cert-curtisalfrey.com:/etc/nginx/conf.d/ssl-cert-curtisalfrey.com
      - multivector-app-data:/app
    ports:
      - "6443:6443"
    networks:
      - data-multivector-network

networks:
  data-multivector-network:

volumes:
  multivector-app-data:
