version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Update the port mapping to use port 80
    environment:
      FLASK_ENV: ${FLASK_ENV}
    volumes:
      - .:/app  # Mount the current directory to /app in the container
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "80:80"
