version: '3'
services:
  app:
    image: data-multivector-image:1.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: 123!z2
    volumes:
      - multivector-app-data:/app
    user: "1000:1000"
    networks:
      - data-multivector-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - /home/ansible/github/my-run-files/nginx.conf:/etc/nginx/nginx.conf
      - /home/ansible/github/my-run-files/security.conf:/etc/nginx/conf.d/security.conf
      - /home/ansible/github/my-run-files/curtisalfrey.com.pem:/etc/nginx/curtisalfrey.com.pem
      - multivector-app-data:/app
    ports:
      - "443:443"
    networks:
      - data-multivector-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  data-multivector-network:
    name: data-multivector-network

volumes:
  multivector-app-data:
    name: multivector-app-data

