version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-multivector-image:1.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: 123!z2
    volumes:
      - multivector-app-data:/app
    networks:
      - data-multivector-network

  nginx:
    image: nginx:latest
    volumes:
      - /path/to/ssl/cert/files:/etc/nginx/conf.d/ssl-cert
      - multivector-app-data:/app
    ports:
      - "6443:6443"  # Use port 6443 for HTTPS
    networks:
      - data-multivector-network

networks:
  data-multivector-network:

volumes:
  multivector-app-data:
