version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-multivector-image:1.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: 123!z2
      UID: 1000
      GID: 1000
    volumes:
      - multivector-app-data:/app
    user: "${UID}:${GID}"  # Use the UID and GID environment variables
    networks:
      - data-multivector-network

  nginx:
    image: nginx:latest
    volumes:
      - /home/ansible/github/Data-MultiVector/nginx.conf:/etc/nginx/conf.d/default.conf
      - multivector-app-data:/app
    ports:
      - "80"
    networks:
      - data-multivector-network

networks:
  data-multivector-network:

volumes:
  multivector-app-data:
