version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-multivector-image:1.0
    ports:
      - "5000:80"
    environment:
      FLASK_ENV: ${FLASK_ENV}
    volumes:
      - app-data:/app
    networks:
      - data-multivector-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - data-multivector-network

networks:
  data-multivector-network:

volumes:
  app-data:
