version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-multivector-image:1.0
    ports:
      - "5000:80"
    environment:
      FLASK_ENV: ${FLASK_ENV}
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    volumes:
      - /home/user/github/Data-MultiVector/:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
