project_folder/
    app.py
    templates/
        index.html
        register.html
        login.html
        dashboard.html
        trash.html
        recovery.html
    static/
        css/
            styles.css
        js/
            script.js
    Dockerfile
