version: '3'
services:
  app:
    image: data-multivector-image:1.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development                                    # development or production
      SECRET_KEY: 123                                           # change me
    volumes:
      - multivector-app-data:/app
    user: "1000:1000"                                           #set user ID
    networks:
      - data-multivector-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  nginx:
    image: nginx:latest
    volumes:
      - /path/to/nginx.conf:/etc/nginx/nginx.conf               # enter all your data into, and then set path to nginx.conf
#      - /path/to/security.conf:/etc/nginx/conf.d/security.conf # remove # in front of - if you want security and update nginx.conf as well 
      - /path/to/ssl/cert/files:/etc/nginx/ssl-cert             # enter host location of ssl pem (.crt .key)
      - multivector-app-data:/app
    ports:
      - "443:443"                                             # set port that you want to use (same as the ngnix.conf)
    networks:
      - data-multivector-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
networks:
  data-multivector-network:
    name: data-multivector-network

volumes:
  multivector-app-data:
    name: multivector-app-data
